services:
    apache:
        image: tugboatqa/httpd
        subpath: true
        domain: "tugboat.local"
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt
